Talkrum.ForumApp/Talkrum.ForumApp/ViewModels/ErrorViewModel.cs
namespace Talkrum.ForumApp.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Talkrum.ForumApp/Talkrum.ForumApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Talkrum.ForumApp.ViewModels;

namespace Talkrum.ForumApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Talkrum.ForumApp/Talkrum.ForumApp/Controllers/TopicController.cs
namespace Talkrum.ForumApp.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

public class TopicController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [Authorize]
    public IActionResult Create()
    {
        return View();
    }

    [Authorize]
    public IActionResult Edit()
    {
        return View();
    }
}

Talkrum.ForumApp/Talkrum.ForumApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<section>
    <div>
        <h1>
            View all Topics
        </h1>
    </div>
    <div>
        <h1>
            Check what's trending
        </h1>
    </div>
    <div>
        <h1>
            Connect with your peers
        </h1>
    </div>
    </div>
</section>

Talkrum.ForumApp/Talkrum.ForumApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Talkrum.ForumApp.Data.Models

@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Talkrum.ForumApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Talkrum.ForumApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Talkrum.ForumApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Topics</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Create">Start New</a>
                        </li> 
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Talkrum.ForumApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Talkrum.ForumApp/Talkrum.ForumApp/Views/Topic/Create.cshtml
@model InputTopicModel
@{
}

<div>
    <h1>Create Topic Here</h1>
</div>

<div class="create-topic">
    <form>
        <hr />
        <div class="create-topic">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating">
                <input asp-for="Title" class="form-control" autocomplete="title" aria-required="true" />
                <label asp-for="Title" class="form-label"></label>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <textarea style="height:15rem;" asp-for="Description" class="form-control" autocomplete="description" aria-required="true"></textarea>
                <label asp-for="Description" class="form-label"></label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="create-submit">
                <button class="create-submit-btn" type="submit" class="w-100 btn btn-lg btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

Talkrum.ForumApp/Talkrum.ForumApp/Views/Topic/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div>
    <h1>
        Edit Topic Here
    </h1>
</div>

Talkrum.ForumApp/Talkrum.ForumApp/Views/Topic/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div>
    <h1>All Topics here</h1>
</div>